In [1]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [4]:
import numpy
n=numpy.arange(27)

In [5]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
type(n)

numpy.ndarray

In [7]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [9]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [3]:
m=numpy.asarray([[123,12,123,12,33],[],[]])

In [6]:
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [7]:
type(m)

numpy.ndarray

In [8]:
import cv2

In [13]:
im_g=cv2.imread("smallgray.png", 1)
print(im_g)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [14]:
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [16]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [17]:
a=[1,2,3]

In [18]:
a[0:2]

[1, 2]

In [20]:
im_g2=cv2.imread("smallgray.png", 0)
print(im_g2)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [23]:
im_g2[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [24]:
im_g2.shape

(3, 5)

In [25]:
im_g2[2,4]

182

In [27]:
for i in im_g2.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [29]:
for i in im_g2.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [50]:
ims=numpy.hstack((im_g2,im_g2,im_g2)) #Horizontal

In [36]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [37]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [46]:
ims2=numpy.vstack((im_g2,im_g2,im_g2)) #Vertical

In [47]:
ims2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [54]:
lst=numpy.hsplit(ims2,5)

In [55]:
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [56]:
lst2=numpy.vsplit(ims2,3)

In [57]:
lst2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [59]:
lst2[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)